name: CI Build
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    environment: build
    # Permissions block is optional, useful for dependabot checks
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - name: Azure login
        uses: azure/login@7184910d9eb2b1c5e48f7073824a90609bb9b6d6 # v2.3.1
        with:
          client-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Setup Java 21
        uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the Maven verify phase
        run: mvn clean verify -DappId=${{ secrets.APP_ID }} -Dcluster=${{ secrets.CLUSTER }} -Dauthority=${{ secrets.TENANT_ID }} -Ddatabase=${{ secrets.DATABASE }} -Dingest=${{ secrets.INGEST }}
        env:
          appId: ${{ secrets.APP_ID }}
          authority: ${{ secrets.TENANT_ID }}
          database: ${{ secrets.DATABASE }}
          cluster: ${{ secrets.CLUSTER }}
          ingest: ${{ secrets.INGEST }}

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@c38a2d74b9840ae8950a4387ae02b637421d0f39 # v1.13.0