name: Upload Release Asset

on:
  release:
    types: [created, edited]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 17
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress clean package -DskipTests
      - name: Get version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
      - name: Github Release
        uses: anton-yurchenko/git-release@ec9c5b5c36b27eaffc628785b9183eae54601200 # v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            target/kafka-sink-ms-fabric-${{ steps.get_version.outputs.VERSION }}-jar-with-dependencies.jar
            target/components/packages/microsoftcorporation-kafka-sink-ms-fabric-${{ steps.get_version.outputs.VERSION }}.zip
        continue-on-error: true
